version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: betalent
      MYSQL_PASSWORD: rootpassword
      tz: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - betalent_network

      

  adonis:    
    container_name: adonis_container
    build:
      context: ./betalent
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./betalent:/app
    command: ["npm", "run", "start"]
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - betalent_network

volumes:
  mysql_data:

networks:
  betalent_network:
