version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: betalent
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - betalent_network

      

  adonis:    
    container_name: adonis_container
    build:
      context: ./betalent
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./betalent:/app
    command: ["npm", "run", "start"]
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - DB_CONNECTION=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=betalent
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - APP_KEY=JsSD0IKWYOhiaH19G5j3NmguWLgXtKrG
      - SECRET=betalent
    depends_on:
      - mysql
    networks:
      - betalent_network

volumes:
  mysql_data:

networks:
  betalent_network:
