import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Client from 'App/Models/Client'

export default class ClientSeeder extends BaseSeeder {
  public async run () {
    await Client.createMany([
      {
        name: 'Joãozinho da Silva',
        email: 'john.silva@mail.com',
        cpf: '480.189.770-38', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf 
      },
      {
        name: 'Mariazinha da Silva',
        email: 'mary.silva@mail.com',
        cpf: '316.300.180-74', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Zequinha da Silva',
        email: 'zack.silva@mail.com',
        cpf: '580.922.130-03', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Joaquim da Silva',
        email: 'joa.silva@mail.com',
        cpf: '707.292.300-40', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Mateus da Silva',
        email: 'mat.silva@mail.com',
        cpf: '632.312.500-06', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Ana da Silva',
        email: 'ana.silva@mail.com',
        cpf: '932.543.450-45', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Pedro da Silva',
        email: 'pedre.silva@mail.com',
        cpf: '158.654.780-12', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Paulo da Silva',
        email: 'pau.silva@mail.com',
        cpf: '123.456.789-00', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      },
      {
        name: 'Lucas da Silva',
        email: 'lucs.silva@mail.com',
        cpf: '321.654.987-11', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      }, 
      {
        name: 'Maria da Silva',
        email: 'mary.silva2@mail.com',
        cpf: '987.654.321-00', // Fake, generated by https://www.4devs.com.br/gerador_de_cpf
      }
    ])
  }
}
