import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Product from 'App/Models/Product'

export default class ProductSeeder extends BaseSeeder {
  public async run () {
    await Product.createMany([
      {
        name: 'Gaming Laptop',
        description: 'High-performance laptop for gaming and professional use.',
        price: 1200,
        stock: 15,
        thumbnail: 'gaming_laptop.jpg',
        brand: 'TechGuru',
      },
      {
        name: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with adjustable DPI settings.',
        price: 50,
        stock: 50,
        thumbnail: 'wireless_mouse.jpg',
        brand: 'ClickMaster',
      },
      {
        name: 'Bluetooth Headphones',
        description: 'Noise-canceling Bluetooth headphones with long battery life.',
        price: 150,
        stock: 30,
        thumbnail: 'bluetooth_headphones.jpg',
        brand: 'SoundWave',
      },
      {
        name: '4K Monitor',
        description: 'Ultra-high-definition monitor with accurate color reproduction.',
        price: 450,
        stock: 25,
        thumbnail: '4k_monitor.jpg',
        brand: 'VisionPro',
      },
      {
        name: 'Mechanical Keyboard',
        description: 'Durable mechanical keyboard with customizable RGB backlighting.',
        price: 100,
        stock: 40,
        thumbnail: 'mechanical_keyboard.jpg',
        brand: 'KeyForge',
      },
      {
        name: 'Smartwatch',
        description: 'Feature-packed smartwatch with fitness tracking and notifications.',
        price: 200,
        stock: 20,
        thumbnail: 'smartwatch.jpg',
        brand: 'TimeMaster',
      },
      {
        name: 'External SSD',
        description: 'High-speed external SSD for data storage and transfer.',
        price: 250,
        stock: 35,
        thumbnail: 'external_ssd.jpg',
        brand: 'DataDrive',
      },
      {
        name: 'Desk Lamp',
        description: 'Adjustable desk lamp with multiple light settings and USB port.',
        price: 60,
        stock: 45,
        thumbnail: 'desk_lamp.jpg',
        brand: 'LightUp',
      },
      {
        name: 'Ergonomic Chair',
        description: 'Comfortable ergonomic chair with lumbar support and adjustable height.',
        price: 300,
        stock: 10,
        thumbnail: 'ergonomic_chair.jpg',
        brand: 'ComfortSeater',
      },
      {
        name: 'USB Hub',
        description: 'Compact USB hub with multiple ports for easy connectivity.',
        price: 30,
        stock: 60,
        thumbnail: 'usb_hub.jpg',
        brand: 'HubLink',
      },
      {
        name: 'Portable Speaker',
        description: 'Compact portable speaker with powerful sound and Bluetooth connectivity.',
        price: 80,
        stock: 55,
        thumbnail: 'portable_speaker.jpg',
        brand: 'SoundBlast',
      },
      {
        name: 'Webcam HD',
        description: 'High-definition webcam for clear video calls and streaming.',
        price: 70,
        stock: 70,
        thumbnail: 'webcam_hd.jpg',
        brand: 'ClearView',
      },
      {
        name: 'Laptop Stand',
        description: 'Adjustable laptop stand to improve ergonomics and cooling.',
        price: 40,
        stock: 65,
        thumbnail: 'laptop_stand.jpg',
        brand: 'ElevateTech',
      },
      {
        name: 'Keyboard Cover',
        description: 'Silicone keyboard cover to protect against spills and dust.',
        price: 20,
        stock: 80,
        thumbnail: 'keyboard_cover.jpg',
        brand: 'ShieldGuard',
      },
      {
        name: 'Gaming Chair',
        description: 'High-back gaming chair with reclining feature and adjustable armrests.',
        price: 350,
        stock: 5,
        thumbnail: 'gaming_chair.jpg',
        brand: 'GameKing',
      },
      {
        name: 'Wireless Charger',
        description: 'Fast wireless charger for smartphones and other devices.',
        price: 25,
        stock: 75,
        thumbnail: 'wireless_charger.jpg',
        brand: 'ChargePro',
        is_deleted: true,
      }
    ])
  }
}
